### PR TITLE
fix: escape error.message on login failure

### LINKED ISSUE #3382: Sanitize error messages before writing to login page
Issue identified by CodeQL in `src/node/util.ts`

See issue explanation and recommendation: https://github.com/cdr/code-server/security/code-scanning/44?query=ref%3Arefs%2Fheads%2Fmain

### PR DESCRIPTION
**Pull request by jsjoeio**
This PR fixes a security issue by sanitizing the `error.message` before sending it back to the client on a login failure.

## Changes
- add function `escapeHtml` + tests
- fix: escape `error.message` before sending to client on login failure

## Checklist
- [x] tested locally
- [x] added a test

Fixes #3382

### CODE REVIEW

File: src/node/util.ts [hunk 1]
```diff
@@ -509,3 +509,17 @@ export const isFile = async (path: string): Promise<boolean> => {
     return false
   }
 }
+
+/**
+ * Escapes any HTML string special characters, like &, <, >, ", and '.
+ *
+ * Source: https://stackoverflow.com/a/6234804/3015595
+ **/
+export function escapeHTML(unsafe: string): string {
```
Comment (jsjoeio) [inline src/node/util.ts:518]: nit: rename to `escapeHtml`

File: test/unit/routes/login.test.ts [hunk 2]
```diff
@@ -34,4 +37,41 @@ describe("login", () => {
...
+
+    // Store whatever might be in here so we can restore it afterward.
+    // TODO: We should probably pass this as an argument somehow instead of
+    // manipulating the environment.
+    const previousEnvPassword = process.env.PASSWORD
+
+    beforeEach(async () => {
+      process.env.PASSWORD = "test"
+      _codeServer = await integration.setup(["--auth=password"], "")
+    })
```
Comment (jsjoeio) [inline test/unit/routes/login.test.ts:57]: we dont' use the password so maybe remove?

File: src/node/util.ts [hunk 3]
```diff
@@ -509,3 +509,17 @@ export const isFile = async (path: string): Promise<boolean> => {
...
+ *
+ * Source: https://stackoverflow.com/a/6234804/3015595
+ **/
+export function escapeHtml(unsafe: string): string {
+  return unsafe
+    .replace(/&/g, "&amp;")
+    .replace(/</g, "&lt;")
+    .replace(/>/g, "&gt;")
+    .replace(/"/g, "&quot;")
+    .replace(/'/g, "&#039;")
```
Comment (oxy) [inline src/node/util.ts:524]: small nit:
I think we could use `&apos;` here instead of `&#039;`, the former is more immediately recognizable in text!

The reason `&#039` is sometimes recommended is because of old browsers that don't support `&apos`, but we basically target the latest versions of Chrome/FF/Safari and have no need to support IE8, so *should* be fine!

**Review by oxy — APPROVED** [review]
one small nit; though I'll leave it to you on if you want it to stay as-is or update the code!

File: src/node/util.ts (hunk 3 above)
Comment (jsjoeio) [reply src/node/util.ts:524]: TIL! Thanks for the suggestion. I'll change that then merge!

File: src/node/routes/login.ts [hunk 4]
```diff
@@ -111,6 +112,7 @@ router.post("/", async (req, res) => {
 
     throw new Error("Incorrect password")
   } catch (error) {
-    res.send(await getRoot(req, error))
+    const htmlToRender = await getRoot(req, error)
```
Comment (kylecarbs) [inline src/node/routes/login.ts:115]: Very minor nit, but this is `renderedHtml`, right?

**Review by kylecarbs — APPROVED** [review]
:lock:

File: src/node/util.ts [hunk 5]
```diff
@@ -509,3 +509,17 @@ export const isFile = async (path: string): Promise<boolean> => {
...
 }
+
+/**
+ * Escapes any HTML string special characters, like &, <, >, ", and '.
+ *
+ * Source: https://stackoverflow.com/a/6234804/3015595
+ **/
+export function escapeHtml(unsafe: string): string {
+  return unsafe
+    .replace(/&/g, "&amp;")
```
Comment (jawnsy) [inline src/node/util.ts:520]: seems kinda unfortunate that there isn't a built-in function for doing this? I'm always wary of escaping things incorrectly, but this seems reasonable enough

**Review by jawnsy — APPROVED** [review]

File: src/node/routes/login.ts (hunk 4 above)
Comment (jsjoeio) [reply src/node/routes/login.ts:115]: lol technically I think you're right. i'll change it

File: src/node/util.ts (hunk 5 above)
Comment (jsjoeio) [reply src/node/util.ts:520]: Well, it is [built-in](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/escape) but:
> Although `escape()` is not strictly deprecated (as in "removed from the Web standards"), it is defined in Annex B of the ECMA-262 standard, whose introduction states:
> Programmers should not use or assume the existence of these features and behaviors when writing new ECMAScript code
