### PR TITLE
Fix GitHub auth

### LINKED ISSUE #1883: Cannot sign in to Github account
Cannot sign in to Github.
When I click on "Clone repository" under SCM tab and provide the repo url and folder, it asks me to sign in to Github.
The authorization page opens in a new tab:
image

After clicking on "Continue", the following error occurs:
image

I tried to generate "Personal Access Token" on Github, then entered that here:
image

This did not work either.

- Web Browser: **Microsoft Egde (Chromium)**
- Local OS: **Windows 10**
- Remote OS: **Ubuntu 18.04.3 (LTS)**
- Remote Architecture: **x64**
- `code-server --version`: **3.4.1**

### LINKED ISSUE #2253: Cannot authenticate with extension github.vscode-pull-request-github
Hi,

Authentification for the extension is failling with this message: 

```
Oh no! An error occurred!
Please restart the sign in process from the editor.

Forbidden
```

Any idea why ?

- Web Browser: Version 75.0.3770.142 (Build officiel) (64 bits)
- Local OS:  Windows 10 Pro 64bits
- Remote OS: Ubuntu 18.04
- Remote Architecture: x86_64
- `code-server --version`: 3.6.1 62735da69466a444561ab9b1115dc7c4d496d455

### PR DESCRIPTION
**Pull request by code-asher**
Closes #1883 
Closes #2253

### CODE REVIEW

File: src/node/routes/vscode.ts [hunk 1]
```diff
@@ -86,6 +90,107 @@ router.get("/webview/*", ensureAuthenticated, async (req, res) => {
...
+      query[key] = req.query[key]
+    }
+  }
+
+  const callback = {
+    uri: {
+      scheme: getFirstString(req.query["vscode-scheme"]) || "code-oss",
+      authority: getFirstString(req.query["vscode-authority"]),
+      path: getFirstString(req.query["vscode-path"]),
+      query: (getFirstString(req.query.query) ? getFirstString(req.query.query) + "&" : "") + qs.stringify(query),
```
Comment (nhooyr) [inline src/node/routes/vscode.ts:154]: If there is no `query`, do we still want `req.query.query` to be added with `&` suffixed? And if it doesn't cause problems, then why don't we just always include `&` instead of checking whether `req.query.query` is there.

File: src/node/routes/vscode.ts [hunk 2]
```diff
@@ -86,6 +90,107 @@ router.get("/webview/*", ensureAuthenticated, async (req, res) => {
...
+    timeout: setTimeout(() => callbacks.delete(id), fetchTimeout),
+  }
+
+  callbacks.set(id, callback)
+  callbackEmitter.emit({ id, callback })
+
+  res.sendFile(path.join(rootPath, "lib/vscode/resources/web/callback.html"))
+})
+
+router.get("/fetch-callback", ensureAuthenticated, async (req, res) => {
```
Comment (nhooyr) [inline src/node/routes/vscode.ts:167]: re `ensureAuthenticated`, is there any reason why we don't include this as part of the router? Every VS Code route should require authentication right?

File: src/node/routes/vscode.ts [hunk 3]
```diff
@@ -86,6 +90,107 @@ router.get("/webview/*", ensureAuthenticated, async (req, res) => {
...
+    res.json(callback.uri)
+  }
+
+  const callback = callbacks.get(id)
+  if (callback) {
+    return send(callback)
+  }
+
+  // VS Code will try again if the route returns no content but it seems more
+  // efficient to just wait on this request for as long as possible?
```
Comment (nhooyr) [inline src/node/routes/vscode.ts:182]: Yea, it'd be the most responsive right? versus VS Code polling.

File: src/node/routes/vscode.ts [hunk 4]
```diff
@@ -86,6 +90,107 @@ router.get("/webview/*", ensureAuthenticated, async (req, res) => {
...
+  const handler = callbackEmitter.event(({ id: emitId, callback }) => {
+    if (id === emitId) {
+      handler.dispose()
+      send(callback)
+    }
+  })
+
+  // If the client closes the connection.
+  req.on("close", () => handler.dispose())
```
Comment (nhooyr) [inline src/node/routes/vscode.ts:191]: 🔥

**Review by nhooyr — COMMENTED** [review]
🥁

File: lib/vscode/extensions/github-authentication/src/githubServer.ts [hunk 5]
```diff
@@ -13,7 +13,7 @@ import Logger from './common/logger';
 const localize = nls.loadMessageBundle();
 
 export const NETWORK_ERROR = 'network error';
-const AUTH_RELAY_SERVER = 'vscode-auth.github.com';
+const AUTH_RELAY_SERVER = 'auth.code-server.dev';
```
[the remark this answers is not in the document]
Comment (code-asher) [reply lib/vscode/extensions/github-authentication/src/githubServer.ts:16]: Right????

File: src/common/util.ts [hunk 6]
```diff
@@ -101,3 +101,14 @@ export const arrayify = <T>(value?: T | T[]): T[] => {
...
+
+/**
+ * Get the first string. If there's no string return undefined.
+ */
+export const getFirstString = (value: string | string[] | object | undefined): string | undefined => {
+  if (Array.isArray(value)) {
+    return value[0]
+  }
+
+  return typeof value !== "object" ? value : undefined
```
[the remark this answers is not in the document]
Comment (code-asher) [reply src/common/util.ts:113]: That...is a good question lol. Will change.

File: src/node/routes/vscode.ts (hunk 1 above)
Comment (code-asher) [reply src/node/routes/vscode.ts:154]: Great point, I tested and it handles cases like `?&code=test` and `?a=b&` just fine so I'll simplify.

File: src/node/routes/vscode.ts (hunk 3 above)
Comment (code-asher) [reply src/node/routes/vscode.ts:182]: Phew, glad you agree, wasn't sure if I was just wrong because I don't know why they implemented a 500ms poll. It floods the logs like crazy.

File: src/node/routes/vscode.ts (hunk 2 above)
Comment (code-asher) [reply src/node/routes/vscode.ts:167]: The root can't be authenticated because it redirects to the login page while the other routes just drop with an error.

We could definitely add middleware that redirects if `/` and otherwise drops though. I kinda like being able to see each route and be sure how the auth is handled on that route but I could go either way.

It's also nice to have the option of an unauthenticated route, I think.

Comment (nhooyr) [reply src/node/routes/vscode.ts:167]: Fine to leave as is then.

**Review by nhooyr — APPROVED** [review]
🚀 🌔 

TO THE MOON!!
