### PR TITLE
Adjust npm package postinstall to install extension dependencies

### LINKED ISSUE #1961: npm module doesn't install extension dependencies
Did a fresh install of the docker image and keep running into the following error:
`Running the contributed command: 'emmet.expandAbbreviation' failed.`

My only setting is:
`{
    "emmet.triggerExpansionOnTab": true
}`

No other extensions installed/enabled. Straight from installation to opening a new html file and trying to expand 
`!` 
or 
`ul>li*5`
results in that error. 

Current version details: 

- code-server: v3.4.0
- VS Code: v1.45.1
- Commit: 69ad52907e8ea109345831d29da5425cb2a55047
- Date: 2020-05-27T23:38:22Z (2 mos ago)

### PR DESCRIPTION
**Pull request by nhooyr**
Closes #1961

### CODE REVIEW

File: ci/build/npm-postinstall.sh [hunk 1]
```diff
@@ -36,6 +36,12 @@ vscode_yarn() {
   yarn --production --frozen-lockfile
   cd extensions
   yarn --production --frozen-lockfile
+  for ext in */; do
+    ext="${ext%/}"
+    echo "extensions/$ext: installing dependencies"
+    yarn --production --frozen-lockfile
```
Comment (code-asher) [inline ci/build/npm-postinstall.sh:42]: I think there's a missing `cd` into the extension dir.

**Review by code-asher — CHANGES_REQUESTED** [review]

File: ci/build/npm-postinstall.sh (hunk 1 above)
Comment (nhooyr) [reply ci/build/npm-postinstall.sh:42]: 🤦🏼

**Review by code-asher — APPROVED** [review]
