### PR TITLE
fix(socket): use xdgBasedir.runtime instead of tmp

### LINKED ISSUE #2200: Fail to create tls-proxy for the second process.
- Web Browser: Chrome
- Local OS: Windows 10
- Remote OS: Ubuntu 16.04
- Remote Architecture: x86_64
- `code-server --version`: 3.5.0

When running two process in the same server by two different users, the second one won't work and gives the following error:

```
discarding socket connection: EACCES: permission denied, unlink '/tmp/code-server/tls-proxy'
```

Notice that the `tls-proxy` is created by the first process. Obviously, it is not accessible by the second process.

After a little research, I find out that this bug is caused by a logic error in `socket.ts`, line 94.

```js
public async findFreeSocketPath(basePath: string, maxTries = 100): Promise<string> {
    let i = 0
    let path = basePath
    while ((await canConnect(path)) && i < maxTries) { // the line with bug
      path = `${basePath}-${++i}`
    }
    return path
  }
```

which should be

```js
public async findFreeSocketPath(basePath: string, maxTries = 100): Promise<string> {
    let i = 0
    let path = basePath
    while (!(await canConnect(path)) && i < maxTries) { // fix the bug
      path = `${basePath}-${++i}`
    }
    return path
  }
```

When the current path is not accessible, then try next one. 

> What is interesting is that when the second user is `root`, then `canConnect` returns `true` in the original code, a new socket file `tls-proxy-1` is created successfully. So that I think the code here should be further modified. We should check if there is a file in `path`. If there is a file here, we should not use this even it is accessible unless the current user is not root.

--- 

There is another problem here:  the directory `/tmp/code-server` is created and owned by the first user, which means this directory is not writable for the second user, so the new socket file `tls-proxy-1` cannot be created. I have to manually change the permissions of the directory to make everything works.

---

Ok I forget one last thing. When I fix every as discribed above, the web client still shows nothing. After checking chrome console, a 404 error occurs for file in path `code-server/release-standalone/dist/pages/pages/vscode.js`. Notice that there are two `pages` here, while the structure of the dist folder is `dist/pages/vscode.js`. I have to manually create another `pages` folder, and copy everything else into it. 

finally, everything works fine.

### PR DESCRIPTION
**Pull request by jsjoeio**
This PR fixes this issue:
```shell
discarding socket connection: EACCES: permission denied, unlink '/tmp/code-server/tls-proxy'
```

by using the `xdgBasedir.runtime` path instead of `/tmp/code-server/tls-proxy`.

## Changes
- update pr template to say default branch
- add `runtime` to `getEnvPaths`
- add test for `getEnvPaths`
- remove use of `tmpdir` in `socket.ts`

  
refactor: use paths.runtime in socket proxyPipe

## Screenshots
image

## Checklist
- [x] tested locally
- [x] added a test
- [x] updated CHANGELOG

Fixes #2200

### CODE REVIEW

File: src/node/socket.ts [hunk 1]
```diff
@@ -76,7 +75,10 @@ export class SocketProxyProvider {
       this._proxyServer = this.findFreeSocketPath(this.proxyPipe)
         .then((pipe) => {
           this.proxyPipe = pipe
-          return Promise.all([fs.mkdir(tmpdir, { recursive: true }), fs.rmdir(this.proxyPipe, { recursive: true })])
+          return Promise.all([
+            fs.mkdir(paths.runtime, { recursive: true }),
+            fs.rmdir(this.proxyPipe, { recursive: true }),
+          ])
```
Comment (jsjoeio) [inline src/node/socket.ts:81]: I was a bit confused looking at this code. Previously, we created a directory with `tmpdir` and removed the `proxyPipe`.

In my change, I have us create a directory at `paths.runtime`.

File: src/node/util.ts [hunk 2]
```diff
@@ -20,19 +22,23 @@ export const paths = getEnvPaths()
  * On MacOS this function gets the standard XDG directories instead of using the native macOS
```
Comment (jawnsy) [inline src/node/util.ts:22]: interesting, I didn't know this! makes sense though. so this means programs use `~/.config` and `~/.local` even on Mac?

File: src/node/util.ts [hunk 3]
```diff
@@ -20,19 +22,23 @@ export const paths = getEnvPaths()
...
   if (process.platform === "win32") {
-    paths = envPaths("code-server", {
-      suffix: "",
-    })
+    paths = {
+      ...envPaths("code-server", {
+        suffix: "",
+      }),
+      runtime: tmpdir,
+    }
```
Comment (jsjoeio) [inline src/node/util.ts:33]: I think this is fine, but would like a second opinion.

File: src/node/util.ts [hunk 4]
```diff
@@ -20,19 +22,23 @@ export const paths = getEnvPaths()
...
   } else {
     if (xdgBasedir.data === undefined || xdgBasedir.config === undefined) {
       throw new Error("No home folder?")
     }
     paths = {
       data: path.join(xdgBasedir.data, "code-server"),
       config: path.join(xdgBasedir.config, "code-server"),
+      runtime: xdgBasedir.runtime ? path.join(xdgBasedir.runtime, "code-server") : tmpdir,
```
Comment (jsjoeio) [inline src/node/util.ts:41]: Originally I broke this out into and `if/else` statement but I feel like this is more condensed and doesn't sacrifice readability.

File: test/unit/node/util.test.ts [hunk 5]
```diff
@@ -0,0 +1,10 @@
+import { getEnvPaths } from "../../../src/node/util"
+
+describe("getEnvPaths", () => {
+  it("should return an object with the data, config and runtime path", () => {
+    const actualPaths = getEnvPaths()
+    expect(actualPaths.hasOwnProperty("data")).toBe(true)
+    expect(actualPaths.hasOwnProperty("config")).toBe(true)
+    expect(actualPaths.hasOwnProperty("runtime")).toBe(true)
+  })
+})
```
Comment (jsjoeio) [inline test/unit/node/util.test.ts:10]: Eventually, we'll add more tests. This was just to get the ball rolling.

File: test/unit/node/util.test.ts [hunk 6]
```diff
@@ -0,0 +1,10 @@
+import { getEnvPaths } from "../../../src/node/util"
+
+describe("getEnvPaths", () => {
+  it("should return an object with the data, config and runtime path", () => {
```
Comment (jawnsy) [inline test/unit/node/util.test.ts:4]: is it worth testing what the actual results would be for a given homedir? These are only checking that the properties are set, not that they're sensible. On the other hand, it also seems sensible to expect that `xdg-basedir` is well-tested, so maybe it doesn't really matter and these tests are good enough

**Review by jawnsy — APPROVED** [review]
Nice :man_dancing:

File: test/unit/node/util.test.ts (hunk 6 above)
Comment (jsjoeio) [reply test/unit/node/util.test.ts:4]: Yes! I think we were reviewing at the same time, but left a comment: https://github.com/cdr/code-server/pull/3304#discussion_r629748398

I agree. We should test the actual paths and simulate different environments.

File: src/node/util.ts (hunk 2 above)
Comment (code-asher) [reply src/node/util.ts:22]: Yeah originally code-server used the other dirs but it was changed to align with command line tools like the ones @jsjoeio mentioned. I think it's a bit of a grey area because you can probably argue code-server is more like an app than a command line tool, but at least this way we can reference a single directory in the docs.

File: test/unit/node/util.test.ts (hunk 6 above)
Comment (code-asher) [reply test/unit/node/util.test.ts:4]: Hmm that's a good point, if we test the actual content it does seem like we're just re-testing `xdg-basedir` to a point which...haha doesn't actually seem to have tests running at the moment: https://github.com/sindresorhus/xdg-basedir/blob/main/test.js

File: CHANGELOG.md [hunk 7]
```diff
@@ -47,6 +52,26 @@ VS Code v0.00.0
...
+
+VS Code v1.56
+
+### New Features
+
+- item
+
+### Bug Fixes
+
+- fix(socket): use xdgBasedir.runtime instead of tmp #3304 @jsjoeio
```
Comment (code-asher) [inline CHANGELOG.md:65]: :fire:

File: src/node/socket.ts (hunk 1 above)
Comment (code-asher) [reply src/node/socket.ts:81]: Ah yup this looks good. We are making sure the directory the socket will go into exists and at the same time removing the old socket file if it exists.

File: src/node/socket.ts [hunk 8]
```diff
@@ -76,7 +75,10 @@ export class SocketProxyProvider {
       this._proxyServer = this.findFreeSocketPath(this.proxyPipe)
         .then((pipe) => {
           this.proxyPipe = pipe
-          return Promise.all([fs.mkdir(tmpdir, { recursive: true }), fs.rmdir(this.proxyPipe, { recursive: true })])
+          return Promise.all([
+            fs.mkdir(paths.runtime, { recursive: true }),
```
Comment (code-asher) [inline src/node/socket.ts:79]: I should have had it like this before:

```suggestion
            fs.mkdir(path.dirname(this.proxyPath), { recursive: true }),
```

File: src/node/util.ts (hunk 3 above)
Comment (code-asher) [reply src/node/util.ts:33]: `xdg-basedir` is not meant to be used on Windows (or technically on Mac according to the docs haha but we use it anyway) so maybe we can use `temp` instead since there doesn't seem to be a runtime concept.

Edit: see suggestion below

File: src/node/util.ts (hunk 4 above)
Comment (code-asher) [reply src/node/util.ts:41]: Upon further thought, let's fall back to `temp` from the `env-paths` module instead of `tmpdir`. It uses a directory per-user so it'll ensure #2200 doesn't keep happening for users without a runtime dir specified.

Maybe something like this? Feel free to do it completely differently haha, I just started writing an example of what I meant and it turned into a whole thing.

```
const paths = envPaths("code-server", { suffix: "" })
const append = (p: string): string => path.join(p, "code-server")
switch (process.platform) {
  case "darwin":
    return {
      // envPaths uses native directories so force Darwin to use the XDG spec
      // to align with other CLI tools.
      data: xdgBasedir.data ? append(xdgBasedir.data) : paths.data,
      config: xdgBasedir.config ? append(xdgBasedir.config) : paths.config,
      // Fall back to temp if there is no runtime dir.
      runtime: xdgBasedir.runtime ? append(xdgBasedir.runtime) : paths.temp,
    }
  case "win32":
    return {
      data: paths.data,
      config: paths.config,
      // Windows doesn't have a runtime dir.
      runtime: paths.temp,
    }
  default:
    return {
      data: paths.data,
      config: paths.config,
      // Fall back to temp if there is no runtime dir.
      runtime: xdgBasedir.runtime ? append(xdgBasedir.runtime) : paths.temp,
    }
}
```

File: test/unit/node/util.test.ts [hunk 9]
```diff
@@ -0,0 +1,15 @@
...
+    const actualPaths = getEnvPaths()
+    const expectedProperties = ["data", "config", "runtime"]
+    expectedProperties.forEach((property) => {
+      // This is a funky way to do it rather than calling hasOwnProperty itself
+      // We do this because of this eslint rule
+      // Link: https://eslint.org/docs/rules/no-prototype-builtins
+      const hasProperty = Object.prototype.hasOwnProperty.call(actualPaths, property)
+      expect(hasProperty).toBe(true)
```
Comment (code-asher) [inline test/unit/node/util.test.ts:12]: Would need to export `Paths` to make this work but one alternative:

```suggestion
      expect(actualPaths[property as keyof Paths]).toBeDefined()
```

**Review by code-asher — CHANGES_REQUESTED** [review]

File: src/node/socket.ts [hunk 10]
```diff
@@ -76,7 +75,10 @@ export class SocketProxyProvider {
       this._proxyServer = this.findFreeSocketPath(this.proxyPipe)
         .then((pipe) => {
           this.proxyPipe = pipe
-          return Promise.all([fs.mkdir(tmpdir, { recursive: true }), fs.rmdir(this.proxyPipe, { recursive: true })])
+          return Promise.all([
+            fs.mkdir(path.dirname(this.proxyPipe), { recursive: true }),
+            fs.rmdir(this.proxyPipe, { recursive: true }),
```
[the remark this answers is not in the document]
Comment (jawnsy) [reply src/node/socket.ts:80]: I have nothing useful to add, please enjoy some art :)

image

[the remark this answers is not in the document]
Comment (code-asher) [reply src/node/socket.ts:80]: Looks perfect!

**Review by code-asher — APPROVED** [review]

**Comment by jsjoeio** [comment]
Moving to draft because I need to write more tests (new change decreases -0.15%). We want increases!

File: test/unit/node/util.test.ts [hunk 11]
```diff
@@ -0,0 +1,147 @@
...
+      })
+    })
+
+    beforeEach(() => {
+      jest.resetModules()
+      jest.mock("env-paths", () => {
+        return () => ({
+          data: "/home/envPath/.local/share",
+          config: "/home/envPath/.config",
+          temp: "/tmp/envPath/runtime",
```
Comment (jsjoeio) [inline test/unit/node/util.test.ts:19]: For whatever reason, when I extract this object into a variable and pass in to the mock, it doesn't work 🤷‍♂️

File: test/unit/node/util.test.ts [hunk 12]
```diff
@@ -0,0 +1,147 @@
...
+      })
+    })
+
+    it("should return the env paths using xdgBasedir", () => {
+      jest.mock("xdg-basedir", () => ({
+        data: "/home/usr/.local/share",
+        config: "/home/usr/.config",
+        runtime: "/tmp/runtime",
+      }))
+      const getEnvPaths = require("../../../src/node/util").getEnvPaths
```
Comment (jsjoeio) [inline test/unit/node/util.test.ts:38]: I have to do this because of: https://github.com/facebook/jest/issues/2582#issuecomment-284514827

**Review by code-asher — APPROVED** [review]

File: src/node/socket.ts (hunk 1 above)
Comment (Atom1985) [reply src/node/socket.ts]: 👍

File: test/unit/node/util.test.ts (hunk 5 above)
Comment (Atom1985) [reply test/unit/node/util.test.ts]: 🤟

File: src/node/socket.ts (hunk 1 above)
Comment (Atom1985) [reply src/node/socket.ts]: 💝

Comment (Atom1985) [reply src/node/socket.ts]: 👍

Comment (Atom1985) [reply src/node/socket.ts]: 👍

Comment (Atom1985) [reply src/node/socket.ts]: 👌

Comment (Atom1985) [reply src/node/socket.ts]: > I was a bit confused looking at this code. Previously, we created a directory with `tmpdir` and removed the `proxyPipe`.
> 
> In my change, I have us create a directory at `paths.runtime`.

**Review by Atom1985 — APPROVED** [review]
👌

**Review by Atom1985 — COMMENTED** [review]
👌
