### PR TITLE
Symlink node_modules.asar to node_modules in lib/vscode

### LINKED ISSUE #2197: Package with node_modules.asar
Currently we patch `require` to use `node_modules` but this breaks if an extension explicitly tries to look in `node_modules.asar` like the bracket pair colorizer plugin:

```
Activating extension 'CoenraadS.bracket-pair-colorizer-2' failed: ENOENT: no such file or directory, open '/usr/lib/code-server/lib/vscode/node_modules.asar/vscode-oniguruma/release/onig.wasm'. _logMessageInConsole @ abstractExtensionService.ts:416
```

We should package `code-server` with that directory.

### PR DESCRIPTION
**Pull request by code-asher**
Closes #2197.

### CODE REVIEW

File: ci/lib.sh [hunk 1]
```diff
@@ -93,3 +94,17 @@ export OS
...
 # Defaults to release
 RELEASE_PATH="${RELEASE_PATH-release}"
+
+# Symlink node_modules.asar to node_modules. VS Code needs a node_modules.asar
+# but that's just a duplicate of stuff we already have in node_modules.
+symlink_asar() {
+  if [ ! -e node_modules.asar ]; then
+    if [ "${WINDIR-}" ]; then
+      # mklink takes the link name first.
+      mklink /J node_modules.asar node_modules
```
Comment (nhooyr) [inline ci/lib.sh:104]: God bless you for trying to support windows @code-asher 

haha

Only benefit to writing scripts in javascript is that they'll work on windows too. Maybe we should consider that or adding something to our scripts to pull in something like `cygwin` to map standard commands for us easily. In fact, given the interpreter here is `bash`, they'd need `cygwin` anyway and so have a working `ln` binary for windows.

File: ci/build/npm-postinstall.sh [hunk 2]
```diff
@@ -41,6 +41,19 @@ main() {
 vscode_yarn() {
   cd lib/vscode
   yarn --production --frozen-lockfile
+
+  # VS Code needs a node_modules.asar but that's just a duplicate of stuff we
```
Comment (nhooyr) [inline ci/build/npm-postinstall.sh:45]: Let's document what `asar` means/why VS code expects it.

File: .gitignore [hunk 3]
```diff
@@ -9,6 +9,7 @@ release-packages/
 release-gcp/
 release-images/
 node_modules
+node_modules.asar
```
Comment (nhooyr) [inline .gitignore:12]:
```suggestion
/lib/vscode/node_modules.asar
```

File: ci/build/npm-postinstall.sh (hunk 2 above)
Comment (nhooyr) [reply ci/build/npm-postinstall.sh:45]: Also should document that this is a copy of the function `symlink_asar` in `lib.sh`

**Review by nhooyr — COMMENTED** [review]
🔥

File: ci/lib.sh (hunk 1 above)
Comment (code-asher) [reply ci/lib.sh:104]: The weird thing about `ln -s` in Windows (using MINGW64) is that when I tested it seems to just copy the directory rather than make a link. Changes to either end don't reflect on the other side.

Comment (nhooyr) [reply ci/lib.sh:104]: weird. does installing `MINGW64` also install `cygwin`?

Comment (code-asher) [reply ci/lib.sh:109]: I think `MINGW64` is a slim fork of `cygwin` but I'm not sure. :thinking: 

What I do is use the `git` installer and it comes with `MINGW64` with `bash` and a bunch of other things.

**Review by nhooyr — APPROVED** [review]
🚀
